#!/bin/sh
set -eu

root="${SNAP}/usr"

if [ -d "${root}/share/darktable/icu" ]; then
  export ICU_DATA="${root}/share/darktable/icu"
fi
if [ -d "${root}/lib/darktable/libgphoto2" ]; then
  export CAMLIBS="${root}/lib/darktable/libgphoto2/2.5.33"
fi
if [ -d "${root}/lib/darktable/libgphoto2_port" ]; then
  export IOLIBS="${root}/lib/darktable/libgphoto2_port/0.12.2"
fi

exec "${root}/bin/darktable" \
  --moduledir "${root}/lib/darktable" \
  --datadir "${root}/share/darktable" \
  --localedir "${root}/share/locale" \
  "$@"
