package(default_visibility = ["//visibility:public"])

exports_files([
    "authors_h.sh",
    "create_version_c.sh",
    "get_last_commit_year.sh",
    "generate_darktablerc.xsl",
    "generate_darktablerc_conf.xsl",
    "generate_prefs.xsl",
    "generate_styles_string.sh",
    "introspection/ast.pm",
    "introspection/code_gen.pm",
    "introspection/parser.pm",
    "introspection/parser.pl",
    "introspection/scanner.pm",
])

filegroup(name = "authors_h", srcs = ["authors_h.sh"])
filegroup(name = "create_version_c", srcs = [
    "create_version_c.sh",
    "get_last_commit_year.sh",
])
filegroup(name = "create_version_c_script", srcs = ["create_version_c.sh"])
filegroup(name = "generate_darktablerc_conf_xsl", srcs = ["generate_darktablerc_conf.xsl"])
filegroup(name = "generate_darktablerc_xsl", srcs = ["generate_darktablerc.xsl"])
filegroup(name = "generate_prefs_xsl", srcs = ["generate_prefs.xsl"])
filegroup(name = "generate_styles_string", srcs = ["generate_styles_string.sh"])
filegroup(
    name = "runtime_tools",
    srcs = [
        "common.sh",
        "extract_wb_from_images.sh",
        "purge_from_cache.sh",
        "purge_non_existing_images.sh",
        "purge_unused_tags.sh",
    ],
)
filegroup(
    name = "introspection_tools",
    srcs = [
        "introspection/ast.pm",
        "introspection/code_gen.pm",
        "introspection/parser.pm",
        "introspection/parser.pl",
        "introspection/scanner.pm",
    ],
)
