package(default_visibility = ["//visibility:public"])

exports_files([
    "authors_h.sh",
    "basecurve/darktable-curve-tool.c",
    "basecurve/darktable-curve-tool-helper",
    "basecurve/exif-wrapper.cpp",
    "basecurve/plot.basecurve",
    "basecurve/plot.tonecurve",
    "create_version_c.sh",
    "get_last_commit_year.sh",
    "generate_darktablerc.xsl",
    "generate_darktablerc_conf.xsl",
    "generate_prefs.xsl",
    "generate_styles_string.sh",
    "introspection/ast.pm",
    "introspection/code_gen.pm",
    "introspection/parser.pm",
    "introspection/parser.pl",
    "introspection/scanner.pm",
    "makeman.sh",
    "noise/darktable-gen-noiseprofile",
    "noise/noiseprofile.c",
    "noise/profiling-shot.xmp",
    "noise/subr.sh",
])

filegroup(
    name = "authors_h",
    srcs = ["authors_h.sh"],
)

filegroup(
    name = "create_version_c",
    srcs = [
        "create_version_c.sh",
        "get_last_commit_year.sh",
    ],
)

filegroup(
    name = "create_version_c_script",
    srcs = ["create_version_c.sh"],
)

filegroup(
    name = "generate_darktablerc_conf_xsl",
    srcs = ["generate_darktablerc_conf.xsl"],
)

filegroup(
    name = "generate_darktablerc_xsl",
    srcs = ["generate_darktablerc.xsl"],
)

filegroup(
    name = "generate_prefs_xsl",
    srcs = ["generate_prefs.xsl"],
)

filegroup(
    name = "generate_styles_string",
    srcs = ["generate_styles_string.sh"],
)

filegroup(
    name = "runtime_tools",
    srcs = [
        "common.sh",
        "extract_wb_from_images.sh",
        "purge_from_cache.sh",
        "purge_non_existing_images.sh",
        "purge_unused_tags.sh",
    ],
)

filegroup(
    name = "basecurve_runtime_tools",
    srcs = [
        "basecurve/darktable-curve-tool-helper",
    ],
)

filegroup(
    name = "basecurve_runtime_data",
    srcs = [
        "basecurve/plot.basecurve",
        "basecurve/plot.tonecurve",
    ],
)

filegroup(
    name = "noise_runtime_tools",
    srcs = [
        "noise/darktable-gen-noiseprofile",
        "noise/profiling-shot.xmp",
        "noise/subr.sh",
    ],
)

filegroup(
    name = "introspection_tools",
    srcs = [
        "introspection/ast.pm",
        "introspection/code_gen.pm",
        "introspection/parser.pl",
        "introspection/parser.pm",
        "introspection/scanner.pm",
    ],
)
